import React from 'react';
import Footer from '../HomepageComponent/Footer';

const TermsConditions = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex-grow relative p-6 md:p-8 max-w-6xl mx-auto bg-[#EFE3C2] bg-opacity-30 overflow-auto">
        {/* Paw Print Decorations */}
        <div className="absolute top-28 left-72 text-[#85A947] text-4xl opacity-40">🐾</div>
        <div className="absolute bottom-6 right-10 text-[#85A947] text-4xl opacity-40">🐾</div>
        <div className="absolute top-40 right-10 text-[#85A947] text-4xl opacity-40">🐾</div>

        <div className="relative z-10">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-black mb-6 md:mb-8 text-[#123524] relative inline-block">
            Terms & Conditions
            <div className="absolute -bottom-2 left-0 right-0 h-1 bg-[#3E7B27]"></div>
          </h1>

          <div className="space-y-8 bg-white rounded-lg shadow-md p-4 md:p-6 border border-[#85A947]">
            <h2 className="text-xl md:text-2xl font-bold text-[#123524]">Terms And Conditions</h2>
            <p className="text-[#3E7B27]">Last Updated: 15-05-2025</p>

            <ol className="list-decimal space-y-4 md:space-y-6 pl-6 text-[#123524]">
              <li className="text-sm md:text-base">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
                applicable and the amended provisions pertaining to electronic records in various statutes as amended by the
                Information Technology Act, 2000. This electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </li>
              <li className="text-sm md:text-base">
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology
                (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy
                and Terms of Use for access or usage of domain name https://doggos-heaven-app-frontend.vercel.app/
                ('Website'), including the related mobile site and mobile application (hereinafter referred to as
                'Platform').
              </li>
              <li className="text-sm md:text-base">
                The Platform is owned by Doggos Heaven Pvt. Ltd., a company incorporated under the Companies Act, 1956 with
                its registered office at Block J, VATIKA INDIA NEXT, Plot 11, near Vatika V'lante, Sector 83, Gurugram,
                Haryana 122004, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
              </li>
              <li className="text-sm md:text-base">
                Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms
                of Use") as applicable to the Platform including the applicable policies which are incorporated herein by
                way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable
                to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the
                Platform Owner and these terms and conditions including the policies constitute Your binding obligations,
                with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services
                (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition
                to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no
                force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your
                responsibility to periodically review these Terms of Use to stay informed of updates.
              </li>
              <li className="text-sm md:text-base">
                For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean
                any natural or legal person who has agreed to become a user/buyer on the Platform.
              </li>
              <li className="text-sm md:text-base">
                ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS
                UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
              </li>
              <li className="text-sm md:text-base">The use of Platform and/or availing of our Services is subject to the following terms of Use:</li>
            </ol>

            <div className="space-y-3 md:space-y-4 pl-6 text-[#3E7B27] text-sm md:text-base">
              <p>
                7.1 To access and use the Services, you agree to provide true, accurate and complete information to us
                during and after registration, and you shall be responsible for all acts done through the use of your
                registered account on the Platform.
              </p>

              <p>
                7.2 Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness,
                performance, completeness or suitability of the information and materials offered on this website or through
                the Services, for any specific purpose. You acknowledge that such information and materials may contain
                inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest
                extent permitted by law.
              </p>

              <p>
                7.3 Your use of our Services and the Platform is solely and entirely at your own risk and discretion for
                which we shall not be liable to you in any manner. You are required to independently assess and ensure that
                the Services meet your requirements.
              </p>

              <p>
                7.4 The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not
                have any authority to claim any intellectual property rights, title, or interest in its contents. The
                contents include and are not limited to the design, layout, look and graphics.
              </p>
            </div>

            <ol start="8" className="list-decimal space-y-4 md:space-y-6 pl-6 text-[#123524] text-sm md:text-base">
              <li>
                We are committed to ethical and humane breeding practices. We do not engage in or support any form of
                abusive breeding. All pets available through our platform are sourced from responsible breeders who adhere
                to the highest standards of animal welfare.
              </li>
              <li>
                The procurement and adoption of pets through our platform are facilitated exclusively via our dedicated pet
                community. This community is built on trust, transparency, and a shared commitment to the well-being of
                animals. We ensure that all pets are placed in loving and suitable homes.
              </li>
            </ol>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsConditions;